### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by amousset** [Normation/cfengine-promise-rust#1]
### Added in CFEngine 3.20

* [ ] [Bodies for custom types](https://cfengine.com/blog/2022/custom-bodies/)

### Added in CFEngine 3.18 (or 3.18.x)

* [x] `interpreter` is now optional, removing from examples
* [x] Custom promises now support the 'log_level' attribute (CFE-3436)
* [x] Custom promise modules using JSON protocol now support data attributes (CFE-3654)
* [x] Custom promise modules using JSON protocol now support slist attributes (CFE-3444)
* [x] `filename` and `line_number` parameters
* [ ] Promise type is now sent to custom promise modules (CFE-3563). One binary could implement several promise types.
  * [x] Read promise_type
  * [ ] Implement multi-type support in executor
  * [ ] Add an example

### Still missing in CFEngine

* [ ] Support for warn_only, it is [still currently not passed](https://tracker.mender.io/browse/CFE-3433) to the custom promise type contrary to what is documented

### Missing in the library

* [ ] Proper logging for executor (using env variable? log to a file?)
* [ ] Check https://github.com/cfengine/masterfiles/blob/master/modules/promises/cfengine.py
* [x] Decide whether to stick to CFEngine generic use case or introduce Rudder-specific stuff
* [ ] Examples of promise type tests (unit and functional)
* [ ] Mechanism for configuration of the behavior
  * [ ] Temporary directory
  * [ ] Node id?
  * [ ] Info about pure-audit vs. action vs. state
* [ ] Add more complex examples
  * [ ] jinja2 templating with https://docs.rs/minijinja
  * [ ] a simple current Rudder resource, like services

* [ ] Pass Rudder parameters to be parsed directly by the executor (tmp dir, Rudder agent version, etc.)

### Won't be implemented (for now)

* [ ] Custom promise types can now report back result classes (CFE-3515). Not relevant, we should stick to outcome classes as much as possible.
* [ ] Support for JSON logs. Cleaner but sends all logs at the end which makes real time log monitoring useless to spot slow steps.
